- hosts: localhost
  connection: local
  gather_facts: False

  tasks:

    - name: Provision a set of instances
      ec2:
         key_name: Keep-Alive
         group: launch-wizard-1
         region: us-west-2
         instance_type: t2.micro
         image: ami-f0091d91
         wait: true
         count: 3
         vpc_subnet_id: subnet-12192c77
         assign_public_ip: yes   
      register: ec2

    - name: Add all instance public IPs to host group
      add_host: hostname={{ item.public_ip }} groups=postgresDBs
      with_items: ec2.instances
    
    - name: Wait for SSH to come up
      wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      with_items: ec2.instances  

    
- hosts: postgresDBs
  user: ec2-user
  sudo: true
  gather_facts: true

  tasks:

    - name: Update packages
      yum: name=* state=latest

    - name: Install docker
      yum: name=docker state=latest    
 
    - name: Start docker service
      service: name=docker state=started 

    - name: docker login
      script: dockerConfig.sh
